### ISSUE TITLE
[Data Preprocessing] Preprocess Data

### ISSUE THREAD

**Issue by yehyunsuh** [yehyunsuh/2023-Fall-CS8395-Final-Project#2]
## What
Preprocess data to have be fed into the model

## Why
Currently there are few problems with dataset.
- Problem1: To few dataset -> Solution: Flip the left knee to right knee.
- Problem2: If we flip, the model will learn the flipped characteristics of the knee -> Solution: Have to delete the parts that can be learnable.
<img width="1163" alt="image" src="https://github.com/yehyunsuh/2023-Fall-CS8395-Final-Project/assets/73840274/8d9866bb-d1d6-4569-83cf-f80b64a0b569">

## TODO
- [x] `data/view_ap/patient_cropped`: Manually crop images that are not cropped properly
- [x] `data/view_ap/patient_cropped_LR`: Manually label all the images that are not labeled in left/right
- [x] `data/view_ap/patient_cropped_LR_removed`: Manually move pre-op image in post-op to pre-op(there were cases where patient had another joint replacement, making a pre-op to be inside post-op) and remove healty side knee + remove noisy images
- [x] Manually annotate all the landmarks that need to be deleted
- [x] `data/view_ap/patient_cropped_LR_removed_erased`: Erase all the unnecessary part
- [x] `data/view_ap/patient_cropped_LR_removed_erased_flipped`, `data/view_ap/image`: Flip all the left knee to right
