### ISSUE TITLE
[Data Preprocessing] Inverting Color, Aligning Bones, Registering Center of Joints

### ISSUE THREAD

**Issue by yehyunsuh** [yehyunsuh/2023-Fall-CS8395-Final-Project#4]
## What
Inverting Color, Aligning Bones, Registering Center of Joints

## Why
To align all the images
 
## TODO
- [x] Check the shape of all the images
- [x] Decide the ratio of the ROI
- [x] Invert color of image
- [x] Align bones
- [x] Register center of joint
- [x] Align + Register

**Comment by garyeechung** [comment]
pre/post of the same patient+side are aligned
76 patient+side, 152 pics
